import { WardrobeItem, DiscoverLook, Outfit, UserProfile } from '../types';

export const INITIAL_USER_PROFILE: UserProfile = {
  name: 'Elena Vance',
  email: 'elena.vance@atelier.io',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
  styleAesthetics: ['Quiet Luxury', 'Minimalist', 'Old Money Tailoring'],
  favoriteColors: ['#F3EFEA', '#1C1C22', '#C5A059', '#3E4E42', '#A37B5C'],
  preferredOccasions: ['Cocktail & Dinner', 'Creative Business', 'Gallery Opening', 'Weekend Brunch'],
  budgetTier: 'Designer Luxury',
  location: 'Milan, Italy',
  weatherUnit: '°C',
  colorSeason: 'Deep Autumn (Warm & Rich)',
  sizing: {
    top: 'S (36 EU)',
    bottom: '26 (38 EU)',
    shoes: '38.5 EU',
    height: "5'9\" (175 cm)",
    fitPreference: 'Relaxed Tailoring',
  },
  isVipMember: true,
  vipTier: 'NIKA Atelier VIP',
  memberSince: 'March 2025',
  stats: {
    totalClosetPieces: 18,
    looksGenerated: 42,
    looksSaved: 14,
    wardrobeUtilization: 86,
  },
};

export const INITIAL_WARDROBE: WardrobeItem[] = [
  {
    id: 'w-1',
    name: 'Cashmere Ribbed Knit',
    category: 'tops',
    subcategory: 'Sweater',
    color: 'Oatmeal Taupe',
    colorHex: '#D6CDC0',
    season: 'Fall/Winter',
    brand: 'Totême',
    imageUrl: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=600&q=80',
    inCloset: true,
    occasions: ['Creative Business', 'Casual Coffee', 'Gallery Opening'],
    timesWorn: 12,
    addedAt: '2025-01-10',
    notes: 'Pure Mongolian cashmere, mock neck cut',
  },
  {
    id: 'w-2',
    name: 'Pleated Wide-Leg Trousers',
    category: 'bottoms',
    subcategory: 'Trousers',
    color: 'Charcoal Noir',
    colorHex: '#25252B',
    season: 'All-Season',
    brand: 'COS Atelier',
    imageUrl: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=600&q=80',
    inCloset: true,
    occasions: ['Creative Business', 'Dinner Date', 'Cocktail'],
    timesWorn: 18,
    addedAt: '2025-01-15',
    notes: 'High-waisted double front pleats, fluid drape',
  },
  {
    id: 'w-3',
    name: 'Double-Breasted Wool Camel Coat',
    category: 'outerwear',
    subcategory: 'Long Coat',
    color: 'Warm Camel',
    colorHex: '#C09363',
    season: 'Fall/Winter',
    brand: 'Max Mara',
    imageUrl: 'https://images.unsplash.com/photo-1539533018447-63fcce667823?auto=format&fit=crop&w=600&q=80',
    inCloset: true,
    occasions: ['All-Occasion', 'Airport Luxe', 'Formal Evening'],
    timesWorn: 24,
    addedAt: '2024-11-20',
    notes: 'Italian virgin wool, belted silhouette',
  },
  {
    id: 'w-4',
    name: 'Pointed Slingback Pumps',
    category: 'footwear',
    subcategory: 'Heels',
    color: 'Midnight Black',
    colorHex: '#141417',
    season: 'All-Season',
    brand: 'Saint Laurent',
    imageUrl: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=600&q=80',
    inCloset: true,
    occasions: ['Cocktail & Dinner', 'Gallery Opening', 'Business Pitch'],
    timesWorn: 9,
    addedAt: '2025-02-01',
    notes: 'Glossy patent calfskin with 65mm kitten heel',
  },
  {
    id: 'w-5',
    name: 'Structured Leather Shoulder Bag',
    category: 'bags',
    subcategory: 'Shoulder Bag',
    color: 'Espresso Bronze',
    colorHex: '#4A3728',
    season: 'All-Season',
    brand: 'The Row',
    imageUrl: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=600&q=80',
    inCloset: true,
    occasions: ['Everyday Luxe', 'Business', 'Dinner'],
    timesWorn: 29,
    addedAt: '2024-10-05',
    notes: 'Smooth nappa leather with minimal gold clasp',
  },
  {
    id: 'w-6',
    name: 'Silk Bias-Cut Slip Dress',
    category: 'dresses',
    subcategory: 'Midi Dress',
    color: 'Champagne Silk',
    colorHex: '#EAE1CE',
    season: 'All-Season',
    brand: 'Reformation',
    imageUrl: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=600&q=80',
    inCloset: true,
    occasions: ['Dinner Date', 'Cocktail', 'Summer Wedding'],
    timesWorn: 6,
    addedAt: '2025-01-22',
    notes: '100% heavyweight mulberry silk',
  },
  {
    id: 'w-7',
    name: 'Sculptural Gold Hoop Earrings',
    category: 'accessories',
    subcategory: 'Jewelry',
    color: 'Brushed 18k Gold',
    colorHex: '#C5A059',
    season: 'All-Season',
    brand: 'Khaite',
    imageUrl: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=600&q=80',
    inCloset: true,
    occasions: ['Everyday Accent', 'Evening'],
    timesWorn: 35,
    addedAt: '2024-09-12',
    notes: 'Hollow architectural curves, lightweight',
  },
  {
    id: 'w-8',
    name: 'Crisp Poplin Button-Down',
    category: 'tops',
    subcategory: 'Shirt',
    color: 'Chalk White',
    colorHex: '#FAF8F5',
    season: 'All-Season',
    brand: 'The Row',
    imageUrl: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=600&q=80',
    inCloset: true,
    occasions: ['Creative Business', 'Weekend Stroll', 'Brunch'],
    timesWorn: 16,
    addedAt: '2025-02-14',
    notes: 'Oversized menswear cut, mother-of-pearl buttons',
  },
  {
    id: 'w-9',
    name: 'Straight-Leg Raw Indigo Denim',
    category: 'bottoms',
    subcategory: 'Jeans',
    color: 'Deep Raw Indigo',
    colorHex: '#2A364F',
    season: 'All-Season',
    brand: 'Khaite',
    imageUrl: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=600&q=80',
    inCloset: true,
    occasions: ['Casual Chic', 'Travel', 'Art Gallery'],
    timesWorn: 22,
    addedAt: '2024-12-01',
    notes: 'Non-stretch Japanese selvedge denim',
  },
  {
    id: 'w-10',
    name: 'Leather Penny Loafers',
    category: 'footwear',
    subcategory: 'Flats',
    color: 'Polished Burgundy Oxblood',
    colorHex: '#4A1D24',
    season: 'All-Season',
    brand: 'Loro Piana',
    imageUrl: 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?auto=format&fit=crop&w=600&q=80',
    inCloset: true,
    occasions: ['Creative Business', 'Weekend Stroll', 'City Tour'],
    timesWorn: 14,
    addedAt: '2025-01-05',
    notes: 'Hand-burnished leather with cushioned insole',
  },
  {
    id: 'w-11',
    name: 'Oversized Wool Blazer',
    category: 'outerwear',
    subcategory: 'Blazer',
    color: 'Dark Taupe Houndstooth',
    colorHex: '#3D3833',
    season: 'Fall/Winter',
    brand: 'Saint Laurent',
    imageUrl: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=600&q=80',
    inCloset: true,
    occasions: ['Creative Business', 'Dinner', 'Gallery Opening'],
    timesWorn: 11,
    addedAt: '2024-11-10',
    notes: 'Strong shoulder pads with relaxed drop hem',
  },
  {
    id: 'w-12',
    name: 'Cashmere Wrap Scarf',
    category: 'accessories',
    subcategory: 'Scarf',
    color: 'Dark Olive Cashmere',
    colorHex: '#3E4E42',
    season: 'Fall/Winter',
    brand: 'Brunello Cucinelli',
    imageUrl: 'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?auto=format&fit=crop&w=600&q=80',
    inCloset: true,
    occasions: ['Travel', 'Cold Weather Coffee'],
    timesWorn: 8,
    addedAt: '2024-12-15',
    notes: 'Ultra-soft featherweight weave',
  }
];

export const INITIAL_SAVED_OUTFITS: Outfit[] = [
  {
    id: 'outfit-default-1',
    title: 'The Milanese Aperitivo',
    tagline: 'Effortless quiet luxury tailored for dusk in Brera',
    occasion: 'Cocktail & Dinner',
    weather: 'Crisp Breeze',
    temperature: '18°C',
    styleAesthetic: 'Quiet Luxury',
    budgetTier: 'Designer Luxury',
    confidenceScore: 98,
    pieces: {
      top: {
        id: 'p-1',
        name: 'Cashmere Ribbed Knit',
        category: 'tops',
        brand: 'Totême',
        material: '100% Mongolian Cashmere',
        color: 'Oatmeal Taupe',
        colorHex: '#D6CDC0',
        imageUrl: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=600&q=80',
        isFromCloset: true,
        closetItemId: 'w-1',
        price: 520,
        retailer: 'SSENSE',
      },
      bottom: {
        id: 'p-2',
        name: 'Pleated Wide-Leg Trousers',
        category: 'bottoms',
        brand: 'COS Atelier',
        material: 'Wool Blend Flannel',
        color: 'Charcoal Noir',
        colorHex: '#25252B',
        imageUrl: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=600&q=80',
        isFromCloset: true,
        closetItemId: 'w-2',
        price: 190,
        retailer: 'COS',
      },
      outerwear: {
        id: 'p-3',
        name: 'Double-Breasted Wool Camel Coat',
        category: 'outerwear',
        brand: 'Max Mara',
        material: 'Virgin Wool',
        color: 'Warm Camel',
        colorHex: '#C09363',
        imageUrl: 'https://images.unsplash.com/photo-1539533018447-63fcce667823?auto=format&fit=crop&w=600&q=80',
        isFromCloset: true,
        closetItemId: 'w-3',
        price: 1890,
        retailer: 'Net-A-Porter',
      },
      shoes: {
        id: 'p-4',
        name: 'Pointed Slingback Pumps',
        category: 'footwear',
        brand: 'Saint Laurent',
        material: 'Patent Leather',
        color: 'Midnight Black',
        colorHex: '#141417',
        imageUrl: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=600&q=80',
        isFromCloset: true,
        closetItemId: 'w-4',
        price: 895,
        retailer: 'Farfetch',
      },
      bag: {
        id: 'p-5',
        name: 'Structured Leather Shoulder Bag',
        category: 'bags',
        brand: 'The Row',
        material: 'Nappa Leather',
        color: 'Espresso Bronze',
        colorHex: '#4A3728',
        imageUrl: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=600&q=80',
        isFromCloset: true,
        closetItemId: 'w-5',
        price: 2450,
        retailer: 'Bergdorf Goodman',
      },
      accessories: [
        {
          id: 'p-6',
          name: 'Sculptural Gold Hoop Earrings',
          category: 'accessories',
          brand: 'Khaite',
          material: '18k Vermeil',
          color: 'Brushed Gold',
          colorHex: '#C5A059',
          imageUrl: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=600&q=80',
          isFromCloset: true,
          closetItemId: 'w-7',
          price: 420,
          retailer: 'MatchesFashion',
        }
      ]
    },
    colorPalette: [
      { name: 'Warm Camel', hex: '#C09363', role: 'Layer' },
      { name: 'Oatmeal Cashmere', hex: '#D6CDC0', role: 'Base' },
      { name: 'Charcoal Noir', hex: '#25252B', role: 'Contrast' },
      { name: 'Champagne Gold', hex: '#C5A059', role: 'Accent' },
    ],
    stylingTips: [
      'Half-tuck the cashmere sweater gently into the front waistband to highlight waist structure while keeping effortless drape.',
      'Drape the camel coat over your shoulders instead of putting arms through the sleeves for modern editorial movement.',
      'Allow the pointed kitten heel to peek just 1.5 inches past the wide trouser cuff.',
      'Brushed gold hoops provide the only metallic warmth needed against the charcoal wool.'
    ],
    silhouetteRationale: 'Plays with volume contrast: the fluidity of wide-leg wool balances the plush texture of the ribbed cashmere, anchored by razor-sharp slingbacks.',
    layeringGuide: 'Base: Mock neck knit. Mid-layer: Tucked trousers with clean line. Outer: Over-the-shoulder camel wool coat. Temperature rated: 14°C to 20°C.',
    isClosetOnly: true,
    savedAt: 'Yesterday, 8:45 PM',
    isFavorite: true,
  },
  {
    id: 'outfit-default-2',
    title: 'The Art Fair Curator',
    tagline: 'Structured architectural tailoring meets relaxed Japanese denim',
    occasion: 'Gallery Opening',
    weather: 'Overcast & Mild',
    temperature: '16°C',
    styleAesthetic: 'Minimalist Avant-Garde',
    budgetTier: 'Elevated Contemporary',
    confidenceScore: 97,
    pieces: {
      top: {
        id: 'p-7',
        name: 'Crisp Poplin Button-Down',
        category: 'tops',
        brand: 'The Row',
        material: 'Egyptian Cotton Poplin',
        color: 'Chalk White',
        colorHex: '#FAF8F5',
        imageUrl: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=600&q=80',
        isFromCloset: true,
        closetItemId: 'w-8',
        price: 690,
        retailer: 'SSENSE',
      },
      bottom: {
        id: 'p-8',
        name: 'Straight-Leg Raw Indigo Denim',
        category: 'bottoms',
        brand: 'Khaite',
        material: 'Selvedge Cotton',
        color: 'Raw Indigo',
        colorHex: '#2A364F',
        imageUrl: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=600&q=80',
        isFromCloset: true,
        closetItemId: 'w-9',
        price: 420,
        retailer: 'Net-A-Porter',
      },
      outerwear: {
        id: 'p-9',
        name: 'Oversized Wool Blazer',
        category: 'outerwear',
        brand: 'Saint Laurent',
        material: 'Houndstooth Wool',
        color: 'Taupe Houndstooth',
        colorHex: '#3D3833',
        imageUrl: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=600&q=80',
        isFromCloset: true,
        closetItemId: 'w-11',
        price: 2190,
        retailer: 'Farfetch',
      },
      shoes: {
        id: 'p-10',
        name: 'Leather Penny Loafers',
        category: 'footwear',
        brand: 'Loro Piana',
        material: 'Oxblood Calfskin',
        color: 'Oxblood Burgundy',
        colorHex: '#4A1D24',
        imageUrl: 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?auto=format&fit=crop&w=600&q=80',
        isFromCloset: true,
        closetItemId: 'w-10',
        price: 980,
        retailer: 'Loro Piana',
      },
      accessories: [
        {
          id: 'p-11',
          name: 'Sculptural Gold Hoop Earrings',
          category: 'accessories',
          brand: 'Khaite',
          material: 'Vermeil',
          color: 'Gold',
          colorHex: '#C5A059',
          imageUrl: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=600&q=80',
          isFromCloset: true,
          closetItemId: 'w-7',
          price: 420,
          retailer: 'MatchesFashion',
        }
      ]
    },
    colorPalette: [
      { name: 'Chalk White', hex: '#FAF8F5', role: 'Base' },
      { name: 'Taupe Houndstooth', hex: '#3D3833', role: 'Layer' },
      { name: 'Raw Indigo', hex: '#2A364F', role: 'Contrast' },
      { name: 'Oxblood Burgundy', hex: '#4A1D24', role: 'Accent' },
    ],
    stylingTips: [
      'Unbutton the top two buttons of the white poplin shirt and roll the blazer cuffs once to reveal the crisp shirt sleeve.',
      'Let the rich oxblood loafers act as the anchor of warmth against cool indigo denim.'
    ],
    silhouetteRationale: 'Strong architectural shoulders offset by clean straight denim lines, creating an effortless intellectual aesthetic.',
    layeringGuide: 'Lightweight crisp poplin under heavy structure houndstooth blazer. Can be accessorized with an espresso leather tote.',
    isClosetOnly: true,
    savedAt: 'Oct 1, 2025',
    isFavorite: false,
  }
];

export const DISCOVER_LOOKS: DiscoverLook[] = [
  {
    id: 'disc-1',
    title: 'The Milanese Quiet Luxury',
    subtitle: 'Understated Italian minimalism in double-faced wool & brushed metallics',
    aesthetic: 'Quiet Luxury',
    season: 'Fall/Winter',
    tags: ['Tailored', 'Warm Neutrals', 'High-Low', 'Day-to-Night'],
    heroImageUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1000&q=85',
    curator: 'NIKA Atelier Milano',
    likes: 1240,
    saves: 840,
    fullOutfit: INITIAL_SAVED_OUTFITS[0],
  },
  {
    id: 'disc-2',
    title: 'Parisian Rive Gauche Chic',
    subtitle: 'Trench drape, crisp Breton stripe, and razor-sharp leather ankle boots',
    aesthetic: 'French Effortless',
    season: 'Autumn Transitional',
    tags: ['French Girl', 'Trench', 'Monochrome', 'Denim'],
    heroImageUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1000&q=85',
    curator: 'Camille Laurent, Paris',
    likes: 2180,
    saves: 1420,
    fullOutfit: {
      ...INITIAL_SAVED_OUTFITS[0],
      id: 'outfit-disc-2',
      title: 'Parisian Rive Gauche Chic',
      tagline: 'Casual elegance designed for bookstore strolls and Saint-Germain terraces',
      occasion: 'Weekend Stroll & Coffee',
      styleAesthetic: 'French Effortless',
      confidenceScore: 99,
    },
  },
  {
    id: 'disc-3',
    title: 'Old Money Hamptons & Riviera',
    subtitle: 'Cream linen, braided leather belts, tortoiseshell eyewear, and boat loafers',
    aesthetic: 'Old Money',
    season: 'Spring/Summer',
    tags: ['Linen', 'Ivory', 'Classic Polo', 'Resort'],
    heroImageUrl: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=1000&q=85',
    curator: 'Julian Vance, Geneva',
    likes: 1890,
    saves: 960,
    fullOutfit: {
      ...INITIAL_SAVED_OUTFITS[1],
      id: 'outfit-disc-3',
      title: 'Riviera Sunset Tailoring',
      tagline: 'Bespoke cream palette framed by rich espresso leather accents',
      occasion: 'Dinner Date',
      styleAesthetic: 'Old Money',
      confidenceScore: 96,
    },
  },
  {
    id: 'disc-4',
    title: 'Tokyo Neo-Tailoring & Street Tech',
    subtitle: 'Sculptural asymmetric pleats, matte nylon outerwear, and lug-sole oxfords',
    aesthetic: 'Streetwear Luxury',
    season: 'All-Season',
    tags: ['Avant-Garde', 'Monochrome Noir', 'Oversized', 'Tokyo'],
    heroImageUrl: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1000&q=85',
    curator: 'Kenzo M., Shibuya',
    likes: 1540,
    saves: 720,
    fullOutfit: {
      ...INITIAL_SAVED_OUTFITS[0],
      id: 'outfit-disc-4',
      title: 'Tokyo Asymmetric Silhouette',
      tagline: 'Dramatic architectural volume and ultra-clean hardware',
      occasion: 'Creative Business',
      styleAesthetic: 'Streetwear Luxury',
      confidenceScore: 97,
    },
  }
];

export const OCCASIONS_LIST = [
  { id: 'cocktail', label: 'Cocktail & Dinner', icon: 'Sparkles', desc: 'Evening elegance with refined edge' },
  { id: 'business', label: 'Creative Business / Pitch', icon: 'Briefcase', desc: 'Authoritative, sharp yet contemporary' },
  { id: 'brunch', label: 'Weekend Brunch & Stroll', icon: 'Coffee', desc: 'Effortless, comfortable luxury' },
  { id: 'gallery', label: 'Art Gallery Opening', icon: 'Palette', desc: 'Curated, expressive, design-forward' },
  { id: 'date', label: 'Romantic Date Night', icon: 'Heart', desc: 'Alluring silhouette with tactile textures' },
  { id: 'airport', label: 'Airport & Travel Luxe', icon: 'Plane', desc: 'First-class cashmere comfort & poise' },
  { id: 'wedding', label: 'Garden / City Wedding', icon: 'Gem', desc: 'Sophisticated guest tailoring or silk' },
  { id: 'party', label: 'After-Dark Party / Club', icon: 'Moon', desc: 'Bold, statement metallics and leather' },
];

export const WEATHER_PRESETS = [
  { id: 'crisp', label: 'Crisp & Breezy', temp: '16°C', desc: 'Ideal for lightweight wool, trench, layering' },
  { id: 'warm', label: 'Sunny & Warm', temp: '25°C', desc: 'Breathable linens, silk midi, sun accents' },
  { id: 'rain', label: 'Rain & Overcast', temp: '12°C', desc: 'Trench coat, structured boots, umbrella chic' },
  { id: 'cold', label: 'Winter Chill', temp: '4°C', desc: 'Heavy cashmere, double-breasted coat, scarf' },
  { id: 'hot', label: 'Summer Heat', temp: '31°C', desc: 'Airy silhouettes, slide sandals, sunhat' },
];

export const STYLE_AESTHETICS = [
  'Quiet Luxury',
  'Minimalist Tailored',
  'Old Money Elegance',
  'French Effortless',
  'Streetwear High-Low',
  'Dark Academia',
  'Coastal Grandmother',
  'Avant-Garde Architectural'
];

export const BUDGET_TIERS = [
  { id: 'conscious', label: 'Conscious & High-Street', range: '$50 – $200 / piece', examples: 'COS, Arket, Mango, Zara' },
  { id: 'contemporary', label: 'Elevated Contemporary', range: '$200 – $600 / piece', examples: 'Totême, Ganni, Anine Bing, Reformation' },
  { id: 'designer', label: 'Designer Luxury', range: '$600 – $2,500 / piece', examples: 'The Row, Khaite, Max Mara, Loro Piana' },
  { id: 'couture', label: 'Haute Couture & Archive', range: '$2,500+ / piece', examples: 'Celine, Chanel, Saint Laurent, Hermès' },
];
